name: Release on Tag

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Build React Project
        working-directory: ./web
        run: |
          bun install
          bun run build

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build application
        run: go build -o sailhost ./cmd/main.go

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sailhost
          path: sailhost

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Gather pull requests
        id: changelog
        run: |
          git fetch --prune --unshallow
          CHANGELOG=$(git log $(git describe --tags --abbrev=0)..HEAD --merges --pretty=format:"- %s")
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            ${{ env.CHANGELOG }}
          draft: false
          prerelease: false

      - name: Upload Application to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: sailhost
          asset_name: sailhost
          asset_content_type: application/octet-stream
